export enum FormFieldProdutor {
    protocolo = 'protocolo',
    no_cpf = 'no_cpf',
    ds_nome = 'ds_nome',
    dt_solicitacao = 'dt_solicitacao',
    co_evento = 'co_evento',
    nu_documento = 'nu_documento',
    ds_orgao_emissor = 'ds_orgao_emissor',
    co_uf_emissor = 'co_uf_emissor',
    co_sexo = 'co_sexo',
    nacionalidade = 'nacionalidade',
    estado_civil = 'estado_civil',
    dt_nascimento = 'dt_nascimento',
    naturalidade = 'naturalidade',
    uf_naturalidade = 'uf_naturalidade',
    uf_pais = 'uf_pais',
    co_municipio = 'co_municipio',
    co_cep = 'co_cep',
    ds_endereco = 'ds_endereco',
    nu_numero = 'nu_numero',
    ds_complemento = 'ds_complemento',
    ds_bairro = 'ds_bairro',
    nu_telefone = 'nu_telefone',
    co_fax = 'co_fax',
    ds_email = 'ds_email'
}

export const FormLabelProdutor = {
    [FormFieldProdutor.protocolo]: 'Protocolo',
    [FormFieldProdutor.no_cpf]: 'Número do CPF',
    [FormFieldProdutor.ds_nome]: 'Nome Completo',
    [FormFieldProdutor.dt_solicitacao]: 'Data da Solicitação',
    [FormFieldProdutor.co_evento]: 'Evento',
    [FormFieldProdutor.nu_documento]: 'Documento de Identificação',
    [FormFieldProdutor.ds_orgao_emissor]: 'Orgão Emissor',
    [FormFieldProdutor.co_uf_emissor]: 'UF Emissor',
    [FormFieldProdutor.co_sexo]: 'Sexo',
    [FormFieldProdutor.nacionalidade]: 'Nacionalidade',
    [FormFieldProdutor.estado_civil]: 'Estado Civil',
    [FormFieldProdutor.dt_nascimento]: 'Data de Nascimento',
    [FormFieldProdutor.naturalidade]: 'Naturalidade',
    [FormFieldProdutor.uf_naturalidade]: 'UF da Naturalidade',
    [FormFieldProdutor.uf_pais]: 'UF do País',
    [FormFieldProdutor.co_municipio]: 'Município',
    [FormFieldProdutor.co_cep]: 'CEP',
    [FormFieldProdutor.ds_endereco]: 'Endereço',
    [FormFieldProdutor.nu_numero]: 'Número',
    [FormFieldProdutor.ds_complemento]: 'Complemento',
    [FormFieldProdutor.ds_bairro]: 'Bairro',
    [FormFieldProdutor.nu_telefone]: 'Telefone',
    [FormFieldProdutor.co_fax]: 'Fax',
    [FormFieldProdutor.ds_email]: 'Email'
};
